"""Render an audit into something a person would put their name on.

The reader is a financial analyst signing off a model they did not build. They are
not debugging a tool; they are deciding whether to trust a number. So the report:

  * leads with the answer, not with methodology
  * gives every finding a cell address and a recomputed consequence in money terms
  * separates what was *proved* from what is merely *suspected*
  * states plainly what was NOT checked, because an audit that hides its blind
    spots is worse than no audit -- it manufactures false confidence
"""

from __future__ import annotations

from datetime import datetime, timezone


def _fmt(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, (int, float)):
        if isinstance(value, float) and value.is_integer():
            value = int(value)
        return f"{value:,}"
    return str(value)


def _delta(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, (int, float)):
        if isinstance(value, float) and value.is_integer():
            value = int(value)
        return f"{value:+,}"
    return str(value)


def render_markdown(report, *, source: str | None = None) -> str:
    """Full audit report as Markdown."""
    proved = report.proved
    unproved = [f for f in report.findings if not f.proved]
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    out: list[str] = []
    add = out.append

    add(f"# Audit — {report.workbook}")
    add("")
    add(f"*Generated by Plumbline on {stamp}. Every finding below is backed by a")
    add("recomputation you can reproduce.*")
    add("")

    if report.skipped:
        add("## Not audited")
        add("")
        add(f"**This workbook could not be audited: {report.skipped}**")
        add("")
        add(_why_skipped(report.skipped))
        return "\n".join(out) + "\n"

    # ---- headline -----------------------------------------------------------
    add("## Summary")
    add("")
    if not proved:
        add(f"**No problems proved.** {report.formula_cells:,} formula cells were checked.")
        if unproved:
            add("")
            add(f"{len(unproved)} cell(s) looked irregular but could not be proved wrong, "
                "so they are listed under *Suspected* rather than reported as errors.")
    else:
        # Only cells with a correction that moves a number today. A dead cell's
        # impact is zero today and unbounded later, which is not a figure to quote.
        money = [
            f.delta for f in proved
            if f.detector == "pattern_break" and isinstance(f.delta, (int, float))
        ]
        add(f"**{len(proved)} proved problem(s)** across {report.formula_cells:,} formula cells.")
        if money:
            largest = max(money, key=abs)
            add("")
            add(f"The largest single correction changes a figure by **{_delta(largest)}**.")
    add("")

    # ---- proved -------------------------------------------------------------
    if proved:
        add("## Proved problems")
        add("")
        add("Each of these was confirmed by recomputing the workbook. The *Effect*")
        add("column is what changes when the cell is corrected.")
        add("")
        for i, f in enumerate(proved, 1):
            add(f"### {i}. `{f.sheet}!{f.cell}` — {_headline(f)}")
            add("")
            add(f"| | |")
            add(f"|---|---|")
            add(f"| **Currently** | `{f.actual}` |")
            add(f"| **Should be** | `{f.expected}` |")
            add(f"| **Value now** | {_fmt(f.baseline_value)} |")
            if f.detector == "pattern_break":
                add(f"| **Value if corrected** | {_fmt(f.repaired_value)} |")
                add(f"| **Effect** | {_delta(f.delta)} |")
            add("")
            add(f"**Why it was flagged.** {f.reason}")
            add("")
            add(f"**Proof.** {f.proof}")
            add("")
            if f.impacted:
                add("**Other cells affected:**")
                add("")
                for ref, before, after in f.impacted[:8]:
                    add(f"- `{ref}`: {_fmt(before)} → {_fmt(after)}")
                add("")

    # ---- suspected ----------------------------------------------------------
    if unproved:
        add("## Suspected, not proved")
        add("")
        add("These cells look irregular, but recomputation did not demonstrate a")
        add("problem. They are shown for a human to judge, and are **not** counted")
        add("as errors.")
        add("")
        add("| Cell | Currently | Expected pattern | Why not proved |")
        add("|---|---|---|---|")
        for f in unproved[:25]:
            reason = f.proof or "no proof attempted"
            add(f"| `{f.sheet}!{f.cell}` | `{_trunc(f.actual)}` | "
                f"`{_trunc(f.expected)}` | {reason} |")
        if len(unproved) > 25:
            add("")
            add(f"*…and {len(unproved) - 25} more.*")
        add("")

    # ---- limits -------------------------------------------------------------
    add("## What this audit did not check")
    add("")
    add("An audit that hides its blind spots manufactures false confidence, so:")
    add("")
    add("- Only **row-wise formula patterns** are checked. A model where every cell")
    add("  in a row is legitimately different has nothing for Plumbline to compare")
    add("  against, and nothing here should be read as clearing it.")
    add("- **Whether the model is the right model** is not assessed. Plumbline checks")
    add("  internal consistency, not whether the business logic is correct.")
    add("- Cells using `OFFSET` or `INDIRECT` are excluded, because they build")
    add("  references while the workbook runs and cannot be analysed statically.")
    if report.dead_candidates:
        add(f"- {report.dead_screened_out} of {report.dead_candidates} typed constants sitting")
        add("  among formulas were set aside as ordinary data rather than frozen")
        add("  formulas, because their values do not match what the surrounding")
        add("  formula would produce.")
    add("- A typed-in value is only reported when the formulas it is compared against")
    add("  sit in the **same block** of its row. That is what stops a data column being")
    add("  measured against a formula block elsewhere in the row, and it has a known")
    add("  cost: where **two or more adjacent cells** were overwritten, or where a whole")
    add("  block was, there is no surviving formula nearby to compare against and the")
    add("  cell is not reported. Wide, contiguous damage is the case this misses.")
    add("")
    add("**A qualified reviewer should confirm each finding before any change is")
    add("made.** Plumbline does not edit workbooks and has not modified this one.")
    add("")

    if source:
        add("---")
        add("")
        add(f"Source file: `{source}`")
    return "\n".join(out) + "\n"


def _headline(f) -> str:
    if f.detector == "dead_cell":
        return "typed-in value where a formula belongs"
    if f.detector == "pattern_break":
        return "formula differs from the rest of its row"
    return f.detector.replace("_", " ")


def _why_skipped(reason: str) -> str:
    if reason.startswith("volatile") or reason.startswith("nondeterministic"):
        return (
            "This workbook produces different numbers each time it recalculates — "
            "usually because it uses `RAND()` or a similar function. Plumbline proves "
            "findings by comparing two calculations, and on a workbook like this the "
            "difference between two runs means nothing. Rather than report proofs that "
            "cannot be reproduced, it declines to audit."
        )
    if reason.startswith("parse"):
        return (
            "The file could not be read as a formula model. It may be corrupt, or it "
            "may use features Plumbline does not support."
        )
    return "See the reason above."


def _trunc(text, n: int = 28) -> str:
    text = str(text)
    return text if len(text) <= n else text[: n - 1] + "…"


#: Markdown is written to a file with an explicit encoding and can be typeset.
#: The console cannot: a legacy Windows code page turns an em dash into a
#: UnicodeEncodeError, and an audit tool that crashes while printing its findings
#: is worse than one that prints them plainly.
_ASCII = {"—": "-", "–": "-", "…": "...", "→": "->", " ": " "}


def _ascii(text: str) -> str:
    for char, plain in _ASCII.items():
        text = text.replace(char, plain)
    return text.encode("ascii", "replace").decode("ascii")


def render_terminal(report) -> str:
    """Compact version for the console. ASCII only, by construction."""
    lines = [f"Plumbline - {report.workbook}"]
    if report.skipped:
        lines.append(f"  not audited: {report.skipped}")
        return _ascii("\n".join(lines))

    proved = report.proved
    lines.append(f"  {report.formula_cells:,} formula cells checked")
    lines.append("")
    if not proved:
        lines.append("  No problems proved.")
    for f in proved:
        lines.append(f"  PROVED  {f.sheet}!{f.cell}  ({_headline(f)})")
        lines.append(f"          is        {_trunc(f.actual, 60)}")
        lines.append(f"          should be {_trunc(f.expected, 60)}")
        lines.append(f"          {f.proof}")
        lines.append("")
    unproved = len(report.findings) - len(proved)
    if unproved:
        lines.append(f"  ({unproved} further cell(s) look irregular but could not be proved)")
    return _ascii("\n".join(lines))
